dashboard/urls.py
from django.urls import path
from .views import DashViewHome, DashViewUpdate, DashViewCreate, delete_event

app_name = 'dash'

urlpatterns = [
    path('', DashViewHome.as_view(), name='home'),
    path('create/', DashViewCreate.as_view(), name='create'),
    path('update/<slug>', DashViewUpdate.as_view(), name="update"),
    path('delete-event/<slug>', delete_event, name="delete")


]

fondem/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import EventList, EventDetail


app_name='website'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name="contact.html"), name='contact'),
    path('news/', EventList.as_view(), name='news'),
    path('single-news/<slug>', EventDetail.as_view(), name='single-news'),
    path('gallery/', TemplateView.as_view(template_name='gallery.html'), name='gallery'),
    path('causes/', TemplateView.as_view(template_name='causes.html'), name='causes'),
    path('donate/', TemplateView.as_view(template_name='donate.html'), name='donate')
]

dashboard/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse


class Event(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()



    def __str__(self):
        return self.title
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Event, self).save(*args, **kwargs)

    
    def get_absolute_url(self):
        return reverse('website:single-news', kwargs={
            'slug':self.slug
        })
    

    def get_absolute_event_url(self):
        return reverse('dash:update', kwargs={
            'slug':self.slug
        })
    
    def get_absolute_delete_url(self):
        return reverse('dash:delete', kwargs={
            'slug':self.slug
        })

dashboard/forms.py
from django import forms
from website.models import Event


class DashboardForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs=({'placeholder':'Titre'})))
    content = forms.CharField(widget=forms.Textarea(attrs=({'rows':"15", 'cols':"6", 'placeholder':"Contenue"})))

website/forms.py
from django import forms
from .models import Event


class DashboardForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs=({'placeholder':'Titre'})))
    content = forms.CharField(widget=forms.Textarea(attrs=({'rows':"15", 'cols':"6", 'placeholder':"Contenue"})))

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.views.generic.edit import UpdateView, DeleteView
from website.models import Event
from .forms import DashboardForm

# Create your views here.
class DashViewCreate(View):


    def get(self, request, *args, **kwargs):
        form = DashboardForm()
        context = {
            'form':form,
        }
        return render(self.request, 'createEvent.html', context)

    def post(self, request, *args, **kwargs):
        if self.request.method == 'POST':
            form = DashboardForm(self.request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
            
                event = Event.objects.create(
                    title=title,
                    content=content
                )
                event.save()
            return redirect("website:news")
        


class DashViewHome(View):
     def get(self, request):
         events = Event.objects.all()
         context = {
             'events':events
         }
         return render(self.request, 'dashboard.html', context)

class DashViewUpdate(UpdateView):
    model = Event
    fields = ['title', 'content']
    template_name = "event_update.html"
    

def delete_event(request, slug):
    event = get_object_or_404(Event, slug=slug)
    a_event = Event.objects.get(slug=event.slug)
    a_event.delete()

    return redirect('dash:home')

website/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, DetailView
from .models import Event
from .forms import DashboardForm
# Create your views here.


    

class EventList(ListView):
    model = Event
    template_name = "news.html"
    context_object_name = "events"
    paginate_by = 3


class EventDetail(DetailView):

    model = Event
    template_name = "single_news.html"
    context_object_name = 'event_detail'

dashboard/templates/dashboard.html
{% extends "base.html" %}

{% load static %} 
{% block content %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

   <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>Liste des Evenements</h1>
                    {% for event in events %}

                    <header class="entry-header d-flex flex-wrap justify-content-between align-items-center">
                            <div class="header-elements">
                                <div class="posted-date">{{ event.pub_date }}</div>

                                <h2 class="entry-title"><a href="{{ event.get_absolute_event_url }}">{{ event.title }}</a></h2>

                            </div>

                        </header>

                    {% endfor %}
                     <span>
                     <a href="{% url 'dash:create' %}">
                            <input class="btn gradient-bg" type="submit" value="Créer un Evenement">
                     </a>
                        </span> 
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .page-header -->

    <div class="contact-page-wrap">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-7">
                    

                </div><!-- .col -->
                <div class="col-12 col-lg-4">
                    
                </div>
    

            </div><!-- .row -->
        </div><!-- .container -->
    </div>

{% endblock content %}

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1>À propos de nous</h1>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .page-header -->

    <div class="welcome-wrap">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6 order-2 order-lg-1">
                    <div class="welcome-content">
                        <header class="entry-header">
                            <h2 class="entry-title">De la vision, mission et valeurs</h2>
                        </header><!-- .entry-header -->

                        <div class="entry-content mt-5">
                            <p><i style="font-weight: bold;">FONDEM-Asbl</i> est une structure qui a était crée à Kinshasa la capital de la République Démocratique du Congo (RDC) le 10 mars 2019 <br> la fondation EMMANUEL-asbl exerce ses activités sur toutes l'étendue de la république Démocratique du congo,
                                mais il peut les étendre partout où le besoin se fait sentir à travers le monde pour des raisons liées à ses activités.<br>
                                En vue de réussir son dessein d'atteindre au mieux les objectifs qu'elle s'est assignés,<br>
                                <i style="font-weight: bold;">FONDEM-Asbl</i> se consacre aux actions sociales orientées vers le soutien des classes défavorisées notamment les personnes vivant avec handicap, les
                                orphelins, les veuves, les femmes battues et les personnes âgées, bref, des personnes vulnérables dépourvues de tout appui social.
                            </p>
                            <h6> <h5 style="font-weight: bold;">La vision</h5> de FONDEM-Asbl est: de vivre dans une humanité respecteuse de la vie et de la justicesociale. <br>
                                <br>
                                <h5 style="font-weight: bold;">La mission</h5> de l'association est de: <br>
                               <ul>
                                   <li>Mettre en oeuvre les droits humains, de la femme et de l'enfant;</li>
                                   <li>Valoriser le bien-être social;</li>
                               </ul>
                               <br>
                               <h5 style="font-weight: bold;" >Nos valeurs</h5>
                               <ul>
                                   <li>Ethique</li>
                                   <li>Justice</li>
                                   <li>Bonne gouvernance</li>
                               </ul>
                                <h3>Des Objectifs</h3>
                                <h6>La FONDEM a pour objectifs:</h6><br>
                                <ul>
                                    <li>Défendre et promouvoir les intérêts des personnes vulnérables;</li>
                                    <li>Lutter  contre toutes formes de violences faites à la femme;</li>
                                    <li>Emanciper la femme, épanouir l'enfant et promouvoir la famille,
                                        notamment par l'organisation des séances de sensibilisation aux droits de 
                                        la femme et de la famille, l'encadrement des filles-mères et des orphelins,
                                        l'apprentissage des métiers et la création des coopératives de développement.
                                    </li>
                                    <li>Combattre la pauvreté, l'analphabétisme et tous autres déficits dans le domaine 
                                        de l'éducation, notamment par la mise à disposition des intrants et matériels agricoles, des 
                                        fournitures scolaires et des matériels didactiques, la contribution aux travaux de restauration et de 
                                        construction des écoles;
                                    </li>
                                    <li>
                                        Promouvoir l'accès aux soins de santé primaire, sensibiliser sur la 
                                        prévention de Maladies Sexuellement Transmissibles et non Transmissibles.
                                    </li>
                                </ul>
                                <br>
                                <br>
                            </h6>
                        </div><!-- .entry-content -->

                    </div><!-- .welcome-content -->
                </div><!-- .col -->

                <div class="col-12 col-lg-6 order-1 order-lg-2">
                    <img style="width: 100%;" src="{% static 'images/welcome.jpg' %}" alt="welcome">
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .home-page-icon-boxes -->

    <div class="about-stats">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="circular-progress-bar">
                        <div class="circle" id="loader_1">
                            <strong class="d-flex justify-content-center"></strong>
                        </div>

                        <h3 class="entry-title">Travail accomplie</h3>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="circular-progress-bar">
                        <div class="circle" id="loader_2">
                            <strong class="d-flex justify-content-center"></strong>
                        </div>

                        <h3 class="entry-title">Amour</h3>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="circular-progress-bar">
                        <div class="circle" id="loader_3">
                            <strong class="d-flex justify-content-center"></strong>
                        </div>

                        <h3 class="entry-title">Idées Innovant</h3>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="circular-progress-bar">
                        <div class="circle" id="loader_4">
                            <strong class="d-flex justify-content-center"></strong>
                        </div>

                        <h3 class="entry-title">Bonne décision</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- <div class="about-testimonial">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-5">
                    <div class="testimonial-cont">
                        <div class="entry-content">
                            <p>We love to help all the children that have problems in the world. After 15 years we have many goals achieved.</p>
                        </div>

                        <div class="entry-footer d-flex flex-wrap align-items-center mt-5">
                            <img src="{% static 'images/testimonial-1.jpg' %}" alt="">

                            <h4>Maria Williams, <span>Volunteer</span></h4>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 offset-lg-2 col-lg-5">
                    <div class="testimonial-cont">
                        <div class="entry-content">
                            <p>We love to help all the children that have problems in the world. After 15 years we have many goals achieved.</p>
                        </div>

                        <div class="entry-footer d-flex flex-wrap align-items-center mt-5">
                            <img src="{% static 'images/testimonial-2.jpg' %}" alt="">

                            <h4>Cristian James, <span>Volunteer</span></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <div class="help-us">
        <div class="container">
            <div class="row">
                <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                    <h2>Aider nous pour pouvoir et aider les autres</h2>

                    <a class="btn orange-border" href="{% url 'website:donate' %}">Faire un don</a>
                </div>
            </div>
        </div>
    </div>



















{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}
<body>
{% include "header.html" %}

    {% block content %}
    
    {% endblock content %}

{% include "footer.html" %}

{% include "script.html" %}

</body>
</html>

templates/header.html
{% load static %}
<header class="site-header">

    <div class="nav-bar">
        <div class="container">
            <div class="row">
                <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                    <div class="site-branding d-flex align-items-center">
                       <a style="text-decoration: none;" class="d-block" href="{% url 'website:home' %}" rel="home">
                           <img src="{% static 'images/logo.png' %}" alt="logo">
                        </a>
                    </div><!-- .site-branding -->

                    <nav class="site-navigation d-flex justify-content-end align-items-center">
                        <ul class="d-flex flex-column flex-lg-row justify-content-lg-end align-content-center">
                            <li class="{% if request.path == '/'%}current-menu-item{% endif %}"><a href="{% url 'website:home' %}">Accueil</a></li>
                            <li class="{% if request.path == 'about/'%}current-menu-item{% endif %}"><a href="{% url 'website:about' %}">Àpropos</a></li>
                            <li ><a href="{% url 'website:causes' %}">Causes</a></li>
                            <li><a href="{% url 'website:gallery' %}">Galleries</a></li>
                            <li><a href="{% url 'website:news' %}">News</a></li>
                            <li class="{% if request.path == 'contact'%}current-menu-item{% endif %}"><a href="{% url 'website:contact' %}">Contact</a></li>
                        </ul>
                    </nav><!-- .site-navigation -->

                    <div class="hamburger-menu d-lg-none">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div><!-- .hamburger-menu -->
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .nav-bar -->
</header><!-- .site-header -->

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="swiper-container hero-slider">
        <div class="swiper-wrapper">
            <div class="swiper-slide hero-content-wrap">
                <img src="{% static 'images/hero.jpg' %}" alt="">

                <div class="hero-content-overlay position-absolute w-100 h-100">
                    <div class="container h-100">
                        <div class="row h-100">
                            <div class="col-12 col-lg-8 d-flex flex-column justify-content-center align-items-start">
                                <header class="entry-header">
                                    <h1>Faire un don</h1>
                                    <h4>Pour les plus démunies</h4>
                                </header><!-- .entry-header -->

                                <div class="entry-content mt-4">
                                    <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus vestibulum mauris quis aliquam. Integer accumsan sodales odio, id tempus ullamcorper</p> -->
                                </div><!-- .entry-content -->

                               
                            </div><!-- .col -->
                        </div><!-- .row -->
                    </div><!-- .container -->
                </div><!-- .hero-content-overlay -->
            </div><!-- .hero-cimgontent-wrap -->
        </div><!-- .swiper-wrapper -->

        <div class="pagination-wrap position-absolute w-100">
            <div class="container">
                <div class="swiper-pagination"></div>
            </div><!-- .container -->
        </div><!-- .pagination-wrap -->

        <!-- Add Arrows -->
        <div class="swiper-button-next flex justify-content-center align-items-center">
            <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1171 960q0 13-10 23l-466 466q-10 10-23 10t-23-10l-50-50q-10-10-10-23t10-23l393-393-393-393q-10-10-10-23t10-23l50-50q10-10 23-10t23 10l466 466q10 10 10 23z"/></svg></span>
        </div>

        <div class="swiper-button-prev flex justify-content-center align-items-center">
            <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1203 544q0 13-10 23l-393 393 393 393q10 10 10 23t-10 23l-50 50q-10 10-23 10t-23-10l-466-466q-10-10-10-23t10-23l466-466q10-10 23-10t23 10l50 50q10 10 10 23z"/></svg></span>
        </div>
    </div><!-- .hero-slider -->

    <div class="home-page-icon-boxes">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
                    <div class="icon-box active">
                        <figure class="d-flex justify-content-center">
                            <img src="{% static 'images/hands-gray.png' %}" alt="">
                            <img src="{% static 'images/hands-white.png' %}" alt="">
                        </figure>

                        <header class="entry-header">
                            <h3 class="entry-title">Dévenir donateur</h3>
                        </header>

                        <div class="entry-content">
                            <p>Supporter la fondation en bien materiel ou argent</p>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
                    <div class="icon-box">
                        <figure class="d-flex justify-content-center">
                            <img src="{% static 'images/donation-gray.png' %}" alt="">
                            <img src="{% static 'images/donation-white.png' %}" alt="">
                        </figure>

                        <header class="entry-header">
                            <h3 class="entry-title">Faire un don avec amour</h3>
                        </header>

                        <div class="entry-content">
                            <p>L'amour c'est de donner sans réserve, votre esprit, votre coeur sans rien démander en retour.</p>
                        </div>
                    </div>
                </div>

            
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .home-page-icon-boxes -->

    <div class="home-page-welcome">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6 order-2 order-lg-1">
                    <div class="welcome-content">
                        <header class="entry-header">
                            <h2 class="entry-title">Bienvenue à FONDEM</h2>
                        </header><!-- .entry-header -->

                        <div class="entry-content mt-5">
                            <p>FONDEM-ASBL a été créée le 08 avril 2019 conformément à la loi du 1ère juillet 1901 et le décret du 16 août 1901 régissant la création d’association en France et a établi son siège social au 21 Rue Alfred Kastler 77176 Savigny-Le-Temple en France et Rue Lac Moero n°267 – Quartier Singa Mupepe – Commune de Lingwala en RDC.</p>
                        </div><!-- .entry-content -->

                        <div class="entry-footer mt-5">
                            <a href="{% url 'website:about' %}" class="btn gradient-bg mr-2">Voir plus</a>
                        </div><!-- .entry-footer -->
                    </div><!-- .welcome-content -->
                </div><!-- .col -->

                <div class="col-12 col-lg-6 mt-4 order-1 order-lg-2">
                    <img style="width: 100%;" src="{% static 'images/welcome.jpg' %}" alt="welcome">
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .home-page-icon-boxes -->

   
    <div class="our-causes">
        <div class="container">
            <div class="row">
                <div class="coL-12">
                    <div class="section-heading">
                        <h2 class="entry-title">Nos causes</h2>
                    </div><!-- .section-heading -->
                </div><!-- .col -->
            </div><!-- .row -->

            <div class="row">
                <div class="col-12">
                    <div class="swiper-container causes-slider">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="cause-wrap">
                                    <figure class="m-0">
                                        <img src="{% static 'images/cause-1.jpg' %}" alt="">

                                        <div class="figure-overlay d-flex justify-content-center align-items-center position-absolute w-100 h-100">
                                            <a href="{% url 'website:donate' %}" class="btn gradient-bg mr-2">Faire un don</a>
                                        </div><!-- .figure-overlay -->
                                    </figure>

                                    <div class="cause-content-wrap">
                                        <header class="entry-header d-flex flex-wrap align-items-center">
                                            <h3 class="entry-title w-100 m-0"><a href="{% url 'website:causes' %}">Aide aux orphelins</a></h3>
                                        </header><!-- .entry-header -->

                                        <div class="entry-content">
                                            <p class="m-0">FONDEM-ASBL a pour objet de secourir les enfants en situation de détresse, les femmes victimes de violences et les personnes vulnérables. </p>
                                        </div><!-- .entry-content -->

                                    </div><!-- .cause-content-wrap -->
                                </div><!-- .cause-wrap -->
                            </div><!-- .swiper-slide -->

                            <div class="swiper-slide">
                                <div class="cause-wrap">
                                    <figure class="m-0">
                                        <img src="{% static 'images/cause-2.jpg' %}" alt="">

                                        <div class="figure-overlay d-flex justify-content-center align-items-center position-absolute w-100 h-100">
                                            <a href="{% url 'website:donate' %}" class="btn gradient-bg mr-2">Faire un don</a>
                                        </div><!-- .figure-overlay -->
                                    </figure>

                                    <div class="cause-content-wrap">
                                        <header class="entry-header d-flex flex-wrap align-items-center">
                                            <h3 class="entry-title w-100 m-0"><a href="{% url 'website:causes' %}">Education pour tous</a></h3>
                                        </header><!-- .entry-header -->

                                        <div class="entry-content">
                                            <p class="m-0">FONDEM-ASBL a pour but d’apporter son aide dans les domaines de l’éducation, de la santé, de la protection ainsi que dans l’amélioration des conditions de vie des personnes citées précédemment afin de leur apporter de l’autonomie et de l’autosuffisance.</p>
                                        </div><!-- .entry-content -->

                                    
                                    </div><!-- .cause-content-wrap -->
                                </div><!-- .cause-wrap -->
                            </div><!-- .swiper-slide -->

                           
                        </div><!-- .swiper-wrapper -->

                    </div><!-- .swiper-container -->

                    <!-- Add Arrows -->
                    <div class="swiper-button-next flex justify-content-center align-items-center">
                        <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1171 960q0 13-10 23l-466 466q-10 10-23 10t-23-10l-50-50q-10-10-10-23t10-23l393-393-393-393q-10-10-10-23t10-23l50-50q10-10 23-10t23 10l466 466q10 10 10 23z"/></svg></span>
                    </div>

                    <div class="swiper-button-prev flex justify-content-center align-items-center">
                        <span><svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M1203 544q0 13-10 23l-393 393 393 393q10 10 10 23t-10 23l-50 50q-10 10-23 10t-23-10l-466-466q-10-10-10-23t10-23l466-466q10-10 23-10t23 10l50 50q10 10 10 23z"/></svg></span>
                    </div>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .our-causes -->

    <div class="home-page-limestone">
        <div class="container">
            <div class="row align-items-end">
                <div class="coL-12 col-lg-6">
                    <div class="section-heading">
                        <h2 class="entry-title">Nous apportons de l'assistance aux enfants de la rue.</h2>

                        {% comment %} <p class="mt-5">Dolor sit amet, consectetur adipiscing elit. Mauris tempus vestib ulum mauris quis aliquam. Lorem ipsum dolor sit amet.</p> {% endcomment %}
                    </div><!-- .section-heading -->
                </div><!-- .col -->

                <div class="col-12 col-lg-6">
                    <div class="milestones d-flex flex-wrap justify-content-between">
                        <div class="col-12 col-sm-4 mt-5 mt-lg-0">
                            <div class="counter-box">
                                <div class="d-flex justify-content-center align-items-center">
                                    <img src="{% static 'images/teamwork.png' %}" alt="">
                                </div>

                                <div class="d-flex justify-content-center align-items-baseline">
                                    <div class="start-counter" data-to="100" data-speed="2000"></div>
                                    <div class="counter-k"></div>
                                </div>

                                <h3 class="entry-title">Enfants aidés</h3><!-- entry-title -->
                            </div><!-- counter-box -->
                        </div><!-- .col -->

                        <div class="col-12 col-sm-4 mt-5 mt-lg-0">
                            <div class="counter-box">
                                <div class="d-flex justify-content-center align-items-center">
                                    <img src="{% static 'images/dove.png' %}" alt="">
                                </div>

                                <div class="d-flex justify-content-center align-items-baseline">
                                    <div class="start-counter" data-to="10" data-speed="2000"></div>
                                </div>

                                <h3 class="entry-title">Volonteur</h3><!-- entry-title -->
                            </div><!-- counter-box -->
                        </div><!-- .col -->
                    </div><!-- .milestones -->
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .our-causes -->
{% endblock content %}